namespace Database.Postgres

module Types =

    type Builtins =
        | BOOL = 16
        | BYTEA = 17
        | CHAR = 18
        | INT8 = 20
        | INT2 = 21
        | INT4 = 23
        | REGPROC = 24
        | TEXT = 25
        | OID = 26
        | TID = 27
        | XID = 28
        | CID = 29
        | JSON = 114
        | XML = 142
        | PG_NODE_TREE = 194
        | SMGR = 210
        | PATH = 602
        | POLYGON = 604
        | CIDR = 650
        | FLOAT4 = 700
        | FLOAT8 = 701
        | ABSTIME = 702
        | RELTIME = 703
        | TINTERVAL = 704
        | CIRCLE = 718
        | MACADDR8 = 774
        | MONEY = 790
        | MACADDR = 829
        | INET = 869
        | ACLITEM = 1033
        | BPCHAR = 1042
        | VARCHAR = 1043
        | DATE = 1082
        | TIME = 1083
        | TIMESTAMP = 1114
        | TIMESTAMPTZ = 1184
        | INTERVAL = 1186
        | TIMETZ = 1266
        | BIT = 1560
        | VARBIT = 1562
        | NUMERIC = 1700
        | REFCURSOR = 1790
        | REGPROCEDURE = 2202
        | REGOPER = 2203
        | REGOPERATOR = 2204
        | REGCLASS = 2205
        | REGTYPE = 2206
        | UUID = 2950
        | TXID_SNAPSHOT = 2970
        | PG_LSN = 3220
        | PG_NDISTINCT = 3361
        | PG_DEPENDENCIES = 3402
        | TSVECTOR = 3614
        | TSQUERY = 3615
        | GTSVECTOR = 3642
        | REGCONFIG = 3734
        | REGDICTIONARY = 3769
        | JSONB = 3802
        | REGNAMESPACE = 4089
        | REGROLE = 409

    let builtinsGetNames (builtins : Builtins) =
        match builtins with
        | Builtins.BOOL -> "BOOL"
        | Builtins.BYTEA -> "BYTEA"
        | Builtins.CHAR -> "CHAR"
        | Builtins.INT8 -> "INT8"
        | Builtins.INT2 -> "INT2"
        | Builtins.INT4 -> "INT4"
        | Builtins.REGPROC -> "REGPROC"
        | Builtins.TEXT -> "TEXT"
        | Builtins.OID -> "OID"
        | Builtins.TID -> "TID"
        | Builtins.XID -> "XID"
        | Builtins.CID -> "CID"
        | Builtins.JSON -> "JSON"
        | Builtins.XML -> "XML"
        | Builtins.PG_NODE_TREE -> "PG_NODE_TREE"
        | Builtins.SMGR -> "SMGR"
        | Builtins.PATH -> "PATH"
        | Builtins.POLYGON -> "POLYGON"
        | Builtins.CIDR -> "CIDR"
        | Builtins.FLOAT4 -> "FLOAT4"
        | Builtins.FLOAT8 -> "FLOAT8"
        | Builtins.ABSTIME -> "ABSTIME"
        | Builtins.RELTIME -> "RELTIME"
        | Builtins.TINTERVAL -> "TINTERVAL"
        | Builtins.CIRCLE -> "CIRCLE"
        | Builtins.MACADDR8 -> "MACADDR8"
        | Builtins.MONEY -> "MONEY"
        | Builtins.MACADDR -> "MACADDR"
        | Builtins.INET -> "INET"
        | Builtins.ACLITEM -> "ACLITEM"
        | Builtins.BPCHAR -> "BPCHAR"
        | Builtins.VARCHAR -> "VARCHAR"
        | Builtins.DATE -> "DATE"
        | Builtins.TIME -> "TIME"
        | Builtins.TIMESTAMP -> "TIMESTAMP"
        | Builtins.TIMESTAMPTZ -> "TIMESTAMPTZ"
        | Builtins.INTERVAL -> "INTERVAL"
        | Builtins.TIMETZ -> "TIMETZ"
        | Builtins.BIT -> "BIT"
        | Builtins.VARBIT -> "VARBIT"
        | Builtins.NUMERIC -> "NUMERIC"
        | Builtins.REFCURSOR -> "REFCURSOR"
        | Builtins.REGPROCEDURE -> "REGPROCEDURE"
        | Builtins.REGOPER -> "REGOPER"
        | Builtins.REGOPERATOR -> "REGOPERATOR"
        | Builtins.REGCLASS -> "REGCLASS"
        | Builtins.REGTYPE -> "REGTYPE"
        | Builtins.UUID -> "UUID"
        | Builtins.TXID_SNAPSHOT -> "TXID_SNAPSHOT"
        | Builtins.PG_LSN -> "PG_LSN"
        | Builtins.PG_NDISTINCT -> "PG_NDISTINCT"
        | Builtins.PG_DEPENDENCIES -> "PG_DEPENDENCIES"
        | Builtins.TSVECTOR -> "TSVECTOR"
        | Builtins.TSQUERY -> "TSQUERY"
        | Builtins.GTSVECTOR -> "GTSVECTOR"
        | Builtins.REGCONFIG -> "REGCONFIG"
        | Builtins.REGDICTIONARY -> "REGDICTIONARY"
        | Builtins.JSONB -> "JSONB"
        | Builtins.REGNAMESPACE -> "REGNAMESPACE"
        | Builtins.REGROLE -> "REGROLE"
        | unkown -> failwithf "Unkown value for a Builtins: %A" unkown
